from __future__ import annotations

import re

_RELATION_SURFACES = {
    "annotate": {
        "annotate",
        "construct",
        "crowdsource",
        "crowdsourced",
        "label",
    },
    "compare": {
        "compare",
        "compared",
        "comparing",
        "comparison",
        "contrast",
        "contrasted",
        "outperform",
        "outperformed",
    },
    "create": {
        "build",
        "built",
        "collect",
        "compile",
        "construct",
        "create",
        "develop",
        "gather",
        "generate",
    },
    "evaluate": {
        "assess",
        "assessed",
        "assessment",
        "benchmark",
        "benchmarked",
        "conduct",
        "conducted",
        "evaluate",
        "evaluated",
        "evaluation",
        "experiment",
        "experimented",
        "experiments",
        "perform",
        "performed",
        "present",
        "presented",
        "report",
        "reported",
        "results",
        "run",
        "ran",
        "test",
        "tested",
    },
    "improve": {
        "benefit",
        "enhance",
        "improve",
        "improvement",
        "improvements",
        "improved",
        "increase",
        "increased",
    },
    "provide": {
        "available",
        "distribute",
        "provide",
        "publish",
        "release",
        "share",
    },
    "train": {
        "finetune",
        "fine-tune",
        "optimize",
        "pretrain",
        "pretrained",
        "train",
    },
    "use": {
        "apply",
        "employ",
        "incorporate",
        "introduce",
        "leverage",
        "rely",
        "use",
        "used",
        "utilize",
    },
    "validate": {"check", "control", "validate", "verify"},
}


def _relation_surface_tokens(relation: str) -> set[str]:
    return _RELATION_SURFACES.get(relation, {relation})


def _object_token(token: str) -> str:
    aliases = {
        "any": "",
        "components": "component",
        "own": "",
        "our": "",
        "their": "",
        "this": "",
        "these": "",
        "those": "",
        "systems": "component",
        "system": "component",
        "packaged": "off_the_shelf",
        "shelf": "off_the_shelf",
        "datasets": "dataset",
        "tasks": "task",
        "author": "",
        "authors": "",
        "current": "",
        "earlier": "",
        "paper": "",
        "previous": "",
        "prior": "",
        "recent": "",
        "study": "",
        "work": "",
    }
    return aliases.get(token, token.rstrip("s") if token.endswith("s") else token)


def _content_tokens(value: str) -> set[str]:
    stopwords = {
        "are",
        "both",
        "across",
        "did",
        "does",
        "all",
        "each",
        "every",
        "five",
        "four",
        "having",
        "multiple",
        "nine",
        "never",
        "no",
        "not",
        "only",
        "overall",
        "seven",
        "six",
        "the",
        "three",
        "they",
        "two",
        "was",
        "were",
        "without",
        "our",
        "own",
        "their",
        "this",
        "these",
        "those",
    }
    return {
        token
        for token in re.findall(r"[a-z0-9]+", str(value or "").lower())
        if len(token) > 2 and token not in stopwords
    }
