from __future__ import annotations

import re

_RELATION_SURFACES = {
    "attribute": {"are", "is", "was", "were"},
    "annotate": {
        "annotate",
        "annotated",
        "annotation",
        "annotations",
        "annotator",
        "annotators",
        "construct",
        "crowdsource",
        "crowdsourced",
        "label",
    },
    "compare": {
        "compare",
        "compared",
        "comparing",
        "comparison",
        "contrast",
        "contrasted",
        "outperform",
        "outperformed",
        "comparable",
        "different",
        "difference",
    },
    "rank": {
        "best",
        "place",
        "placed",
        "position",
        "positions",
        "rank",
        "ranked",
        "ranking",
        "winner",
        "winning",
    },
    "contain": {
        "combine",
        "combined",
        "comprises",
        "consume",
        "consumes",
        "contain",
        "contains",
        "has",
        "have",
        "include",
        "includes",
        "involve",
        "involves",
        "merge",
        "merged",
    },
    "create": {
        "add",
        "added",
        "build",
        "built",
        "collect",
        "compile",
        "construct",
        "create",
        "creation",
        "develop",
        "gather",
        "generate",
        "introduce",
        "introduced",
    },
    "evaluate": {
        "accuracies",
        "accuracy",
        "assess",
        "assessed",
        "assessment",
        "benchmark",
        "benchmarked",
        "conduct",
        "conducted",
        "evaluate",
        "evaluated",
        "evaluation",
        "experiment",
        "experimented",
        "experiments",
        "perform",
        "performance",
        "performed",
        "present",
        "presented",
        "report",
        "reported",
        "results",
        "score",
        "scores",
        "run",
        "ran",
        "test",
        "tested",
    },
    "improve": {
        "benefit",
        "effective",
        "effectiveness",
        "enhance",
        "help",
        "helpful",
        "improve",
        "improvement",
        "improvements",
        "improved",
        "increase",
        "increased",
    },
    "demonstrate": {
        "believe",
        "demonstrate",
        "establish",
        "hypothesize",
        "prove",
        "show",
    },
    "inspect": {
        "analyse",
        "analyze",
        "examine",
        "explore",
        "explored",
        "extract",
        "extracted",
        "extraction",
        "inspect",
        "investigate",
        "study",
    },
    "learn": {
        "capture",
        "captured",
        "captures",
        "learn",
        "learned",
        "model",
        "modeled",
        "modelled",
        "modeling",
        "modelling",
        "represent",
        "represented",
        "represents",
    },
    "provide": {
        "available",
        "distribute",
        "provide",
        "publish",
        "release",
        "share",
    },
    "train": {
        "finetune",
        "fine-tune",
        "optimize",
        "pre-training",
        "pretrain",
        "pretrained",
        "train",
    },
    "use": {
        "apply",
        "employ",
        "incorporate",
        "leverage",
        "rely",
        "use",
        "used",
        "utilize",
    },
    "validate": {"check", "control", "validate", "verify"},
}


def _relation_surface_tokens(relation: str) -> set[str]:
    return _RELATION_SURFACES.get(relation, {relation})


def _object_token(token: str) -> str:
    aliases = {
        "any": "",
        "some": "",
        "accuracies": "performance",
        "accuracy": "performance",
        "automatic": "",
        "based": "",
        "characters": "text",
        "character": "text",
        "components": "component",
        "corpora": "corpus",
        "evaluations": "metric",
        "evaluation": "metric",
        "images": "image",
        "measures": "metric",
        "measure": "metric",
        "metrics": "metric",
        "models": "model",
        "implementations": "baseline",
        "implementation": "baseline",
        "overlap": "",
        "performances": "performance",
        "results": "performance",
        "result": "performance",
        "scores": "metric",
        "score": "metric",
        "samples": "dataset",
        "sample": "dataset",
        "specific": "",
        "sota": "baseline",
        "coherent": "realistic",
        "competitive": "realistic",
        "readable": "realistic",
        "visual": "image",
        "visuals": "image",
        "words": "text",
        "word": "text",
        "own": "",
        "our": "",
        "their": "",
        "this": "",
        "these": "",
        "those": "",
        "systems": "component",
        "system": "component",
        "packaged": "off_the_shelf",
        "shelf": "off_the_shelf",
        "datasets": "dataset",
        "tasks": "task",
        "author": "",
        "authors": "",
        "current": "",
        "earlier": "",
        "paper": "",
        "previous": "",
        "prior": "",
        "recent": "",
        "study": "",
        "work": "",
    }
    return aliases.get(token, token.rstrip("s") if token.endswith("s") else token)


def _content_tokens(value: str) -> set[str]:
    stopwords = {
        "and",
        "are",
        "both",
        "across",
        "did",
        "due",
        "does",
        "all",
        "each",
        "every",
        "five",
        "four",
        "from",
        "for",
        "having",
        "multiple",
        "nine",
        "never",
        "no",
        "not",
        "only",
        "overall",
        "commonly",
        "seven",
        "six",
        "some",
        "such",
        "that",
        "the",
        "three",
        "they",
        "two",
        "was",
        "were",
        "without",
        "our",
        "own",
        "their",
        "this",
        "these",
        "those",
        "very",
    }
    return {
        token
        for token in re.findall(r"[a-z0-9]+", str(value or "").lower())
        if len(token) > 2 and token not in stopwords
    }
