from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from sidecar.server import create_app

GENERATED_CONTRACT_PATH = (
    Path(__file__).resolve().parents[1] / "shared" / "api-contracts.generated.ts"
)
HEADER = """// Generated from the MARA Desktop Sidecar OpenAPI schema.
// Run `npm run contracts:generate`; do not edit this file manually.

"""


class _SchemaApplicationService:
    def get_doctor(self) -> dict[str, Any]:
        raise AssertionError("Schema generation must not call application services")

    def list_files(self) -> list[dict[str, Any]]:
        raise AssertionError("Schema generation must not call application services")

    def list_sessions(self) -> list[dict[str, Any]]:
        raise AssertionError("Schema generation must not call application services")

    def index_files(
        self,
        paths: list[str],
        *,
        reindex: bool = False,
    ) -> dict[str, list[dict[str, Any]]]:
        raise AssertionError("Schema generation must not call application services")

    def delete_file(self, file_id: str) -> list[dict[str, str]]:
        raise AssertionError("Schema generation must not call application services")


def _typescript_literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(value, ensure_ascii=False)


def _schema_type(schema: dict[str, Any]) -> str:
    reference = schema.get("$ref")
    if reference:
        return str(reference).rsplit("/", 1)[-1]

    if "enum" in schema:
        return " | ".join(_typescript_literal(item) for item in schema["enum"])

    alternatives = schema.get("anyOf") or schema.get("oneOf")
    if alternatives:
        rendered = list(dict.fromkeys(_schema_type(item) for item in alternatives))
        return " | ".join(rendered)

    schema_type = schema.get("type")
    if schema_type == "array":
        return f"Array<{_schema_type(schema.get('items', {}))}>"
    if schema_type == "object":
        if schema.get("additionalProperties"):
            value_type = _schema_type(schema["additionalProperties"])
            return f"Record<string, {value_type}>"
        return _inline_object(schema)
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    return "unknown"


def _inline_object(schema: dict[str, Any]) -> str:
    properties = schema.get("properties", {})
    if not properties:
        return "Record<string, unknown>"
    required = set(schema.get("required", []))
    fields = [
        f"{name}{'' if name in required else '?'}: {_schema_type(value)};"
        for name, value in sorted(properties.items())
    ]
    return "{ " + " ".join(fields) + " }"


def _component(name: str, schema: dict[str, Any]) -> str:
    properties = schema.get("properties")
    if schema.get("type") != "object" or not properties:
        return f"export type {name} = {_schema_type(schema)};\n"

    required = set(schema.get("required", []))
    lines = [f"export type {name} = {{"]
    for property_name, property_schema in sorted(properties.items()):
        optional = "" if property_name in required else "?"
        lines.append(f"  {property_name}{optional}: {_schema_type(property_schema)};")
    lines.append("};")
    return "\n".join(lines) + "\n"


def generate_typescript_contracts() -> str:
    schema = create_app(
        "schema-generation",
        _SchemaApplicationService(),
    ).openapi()
    components = schema["components"]["schemas"]
    rendered = [
        _component(name, component) for name, component in sorted(components.items())
    ]
    return HEADER + "\n".join(rendered)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate TypeScript contracts from the Sidecar OpenAPI schema."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the checked-in generated contracts differ.",
    )
    return parser.parse_args()


def main() -> int:
    content = generate_typescript_contracts()
    if parse_args().check:
        if (
            not GENERATED_CONTRACT_PATH.exists()
            or GENERATED_CONTRACT_PATH.read_text(encoding="utf-8") != content
        ):
            print(
                "Generated Sidecar contracts are stale. "
                "Run `npm run contracts:generate`."
            )
            return 1
        print("Generated Sidecar contracts match OpenAPI.")
        return 0

    GENERATED_CONTRACT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {GENERATED_CONTRACT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
