// Generated from the MARA Desktop Sidecar OpenAPI schema.
// Run `npm run contracts:generate`; do not edit this file manually.

export type DoctorPayload = {
  app_name: string;
  default_user_id: string;
  embedding_default: string;
  file_count: number;
  graph_cache_dir: string;
  index_id: number | null;
  index_name: string;
  issues: Array<string>;
  llm_default: string;
  ok: boolean;
  session_count: number;
  warnings: Array<string>;
};

export type DoctorResponse = {
  doctor: DoctorPayload;
  request_id: string;
};

export type FileListResponse = {
  files: Array<FileRecord>;
  request_id: string;
};

export type FileRecord = {
  date_created: string | null;
  file_id: string;
  loader: string;
  name: string;
  size: number;
  tokens: number;
};

export type RuntimeHealth = {
  capabilities: Array<string>;
  protocol: number;
  request_id: string;
  state: string;
  version: string;
};

export type SessionListResponse = {
  request_id: string;
  sessions: Array<SessionSummary>;
};

export type SessionSummary = {
  conversation_id: string;
  date_created: string | null;
  date_updated: string | null;
  graph_source_count: number;
  is_public: boolean;
  message_count: number;
  name: string;
  origin: string;
};

export type SidecarError = {
  code: string;
  details: unknown | null;
  message: string;
  request_id: string;
  retryable: boolean;
};
