// Generated from the MARA Desktop Sidecar OpenAPI schema.
// Run `npm run contracts:generate`; do not edit this file manually.

export type DoctorPayload = {
  app_name: string;
  default_user_id: string;
  embedding_default: string;
  embedding_model: string;
  embedding_provider: string;
  file_count: number;
  graph_cache_dir: string;
  index_id: number | null;
  index_name: string;
  indexing_action: "none" | "configure_embedding" | "repair_installation" | "check_connection" | "check_source_permissions" | "choose_source_again" | "retry" | "free_storage" | "contact_support";
  indexing_issue_code: string | null;
  indexing_message: string;
  indexing_ready: boolean;
  indexing_retryable: boolean;
  issues: Array<string>;
  llm_default: string;
  ok: boolean;
  query_action: "none" | "configure_llm" | "configure_credentials" | "check_model_access" | "repair_installation" | "check_connection" | "close_extra_instance" | "check_data_permissions" | "free_storage" | "repair_state" | "retry";
  query_issue_code: string | null;
  query_message: string;
  query_model: string;
  query_persistence_action: "none" | "close_extra_instance" | "check_data_permissions" | "free_storage" | "repair_state" | "retry";
  query_persistence_issue_code: string | null;
  query_persistence_message: string;
  query_persistence_ready: boolean;
  query_persistence_retryable: boolean;
  query_provider: string;
  query_ready: boolean;
  query_retryable: boolean;
  request_id: string;
  route_fingerprint: string;
  session_count: number;
  settings_revision: string;
  sidecar_pid: number;
  warnings: Array<string>;
};

export type DoctorResponse = {
  doctor: DoctorPayload;
  request_id: string;
};

export type FileBatchDeleteRequest = {
  file_ids: Array<string>;
};

export type FileDeleteResponse = {
  deleted_file_ids: Array<string>;
  request_id: string;
};

export type FileListResponse = {
  files: Array<FileRecord>;
  request_id: string;
};

export type FileRecord = {
  date_created: string | null;
  file_id: string;
  loader: string;
  name: string;
  size: number;
  tokens: number;
};

export type ImportCapabilities = {
  supported_extensions: Array<string>;
};

export type ImportCapabilitiesResponse = {
  import_capabilities: ImportCapabilities;
  request_id: string;
};

export type IndexTask = {
  completed_files: number;
  created_at: string;
  error: IndexTaskError | null;
  failure_count: number;
  failures: Array<IndexTaskFailure>;
  file_names: Array<string>;
  retryable: boolean;
  stage: string;
  status: "queued" | "running" | "partial" | "success" | "failed" | "cancelled";
  success_count: number;
  task_id: string;
  total_files: number;
  updated_at: string;
  version: number;
};

export type IndexTaskCreateRequest = {
  paths: Array<string>;
  reindex?: boolean;
};

export type IndexTaskError = {
  code: string;
  message: string;
  retryable: boolean;
};

export type IndexTaskFailure = {
  code: string;
  message: string;
  name: string;
  retryable: boolean;
};

export type IndexTaskResponse = {
  request_id: string;
  task: IndexTask;
};

export type LatestIndexTaskResponse = {
  request_id: string;
  task: IndexTask | null;
};

export type LatestQueryTaskResponse = {
  request_id: string;
  task: QueryTask | null;
};

export type QueryCitation = {
  citation_id: string;
  element_id?: string | null;
  file_id: string;
  file_name: string;
  page_label?: string | null;
  quote?: string | null;
};

export type QueryPersistenceDiagnostic = {
  errno: number | null;
  fingerprint: string;
  operation: "write_temp" | "flush" | "atomic_replace" | "load" | "unknown";
  post_failure_probe: "not_run" | "ready" | "write_blocked" | "replace_blocked" | "flush_blocked";
  retry_count: number;
  smoke_mode: boolean;
  winerror: number | null;
};

export type QueryTask = {
  answer: string;
  answer_saved: boolean;
  citations: Array<QueryCitation>;
  conversation_id: string;
  created_at: string;
  error: QueryTaskError | null;
  prompt: string;
  qa_scope: "document" | "multi_document";
  retry_of_task_id: string | null;
  retryable: boolean;
  route_fingerprint: string;
  route_model: string;
  route_provider: string;
  selected_file_ids: Array<string>;
  settings_revision: string;
  sidecar_pid: number;
  stage: string;
  status: "queued" | "running" | "success" | "failed" | "cancelled";
  task_id: string;
  terminal_outcome: "" | "answered" | "safe_abstention" | "execution_failed" | "timeout" | "cancelled";
  terminal_outcome_reason: string;
  terminal_semantic_commit: Record<string, unknown>;
  updated_at: string;
  version: number;
};

export type QueryTaskCreateRequest = {
  conversation_id: string;
  prompt: string;
  selected_file_ids: Array<string>;
};

export type QueryTaskError = {
  code: string;
  diagnostic?: string | null;
  message: string;
  persistence?: QueryPersistenceDiagnostic | null;
  provider_request_id?: string | null;
  retryable: boolean;
};

export type QueryTaskResponse = {
  request_id: string;
  task: QueryTask;
};

export type RuntimeHealth = {
  capabilities: Array<string>;
  model_settings_revision: string | null;
  protocol: number;
  request_id: string;
  state: string;
  version: string;
};

export type SessionCreateRequest = Record<string, never>;

export type SessionDeleteResponse = {
  deleted_conversation_id: string;
  request_id: string;
};

export type SessionDetail = {
  conversation_id: string;
  date_created: string | null;
  date_updated: string | null;
  graph_source_ids: Array<string>;
  is_public: boolean;
  messages: Array<SessionMessage>;
  name: string;
  origin: string;
};

export type SessionDetailResponse = {
  request_id: string;
  session: SessionDetail;
};

export type SessionListResponse = {
  request_id: string;
  sessions: Array<SessionSummary>;
};

export type SessionMessage = {
  content: string;
  role: "user" | "assistant";
};

export type SessionRenameRequest = {
  name: string;
};

export type SessionSummary = {
  conversation_id: string;
  date_created: string | null;
  date_updated: string | null;
  graph_source_count: number;
  is_public: boolean;
  message_count: number;
  name: string;
  origin: string;
};

export type SidecarError = {
  code: string;
  details: unknown | null;
  message: string;
  request_id: string;
  retryable: boolean;
};
